server:
  port: 9090

app:
  file:
    upload-path: /home/xiao/web_app_test/xm-blog/files/ # 上传文件的路径
# 数据库配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
      pool-name: HikariCP
      validation-timeout: 5000
    driver-class-name: com.mysql.cj.jdbc.Driver
    # username: root   #你本地的数据库用户名
    # password: 19991210 #你本地的数据库密码
    # url: jdbc:mysql://localhost:3306/xm-blog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    
    username: admin
    password: Xbx123456# #你本地的数据库密码
    url: jdbc:mysql://database-1.c5i6wwwkqmm9.ap-northeast-1.rds.amazonaws.com:3306/xm-blog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
      
    # Add Redis configuration
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  cache:
    type: redis
    redis:
      key-prefix: xm-blog
      # time-to-live: 60000
      cache-null-values: false
      use-key-prefix: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: xm-blog

ip: 216.238.80.124